# model: 
#   type: 'bayesian'
#   model: 'graph_tf'
#   #BFN 
#   t_min: 1.0e-2
#   #Prior
#   transition: 'uniform'
model:
  d_embedding: 256
  d_hidden: 128
  n_layer: 5
  attention: True
  loss: "softmax"     # "softmax", "BCE"
  threshold: 0.5
data:
  data_dir: "core/dataset/data/processed/"
  tokenizer: "word_based"        # "word_based", "pretrained"
  # pretrained_name: "bert"
  min_sentence_len: 10
  # max_sentence_len:
  unk_max_frequency: 3
  labels:
    - enraged_face 
    - face_holding_back_tears
    - face_savoring_food
    - face_with_tears_of_joy 
    - fearful_face
    - hot_face 
    - smiling_face_with_halo
    - loudly_crying_face
    - smiling_face_with_sunglasses
    - thinking_face